apiVersion: v1
kind: Service
metadata:
  name: vproapp
spec:
  type: 
  selector:
    app: vproapp
  ports:
    - port: 8080         # Service Port
      targetPort: vproapp-port  # Container Port
      protocol: TCP
  type: NodePort  
