apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  type: 
  selector:
    app: vprodb
  ports:
    - port: 3306         # Service Port
      targetPort: vprodb-port  # Container Port
      protocol: TCP
  selector:
      app: vprodb
  type: ClusterIP  
