apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  type: 
  selector:
    app: vprormq
  ports:
    - port: 5672         # Service Port
      targetPort: vpromq-port  # Container Port
      protocol: TCP
  type: ClusterIP  
